name: Pull Request Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: github.repository == 'gavfu/chzhshch-blog'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Build for production
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build