name: Github Pages Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'gavfu/chzhshch-blog'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Build for production
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build

      - name: Deploy Gh-Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: decooio/chzhshch-blog-deploy
          publish_branch: main
          publish_dir: ./build
          cname: chzhshch.blog